# .readthedocs.yml
# Read the Docs configuration file

# Details
# - https://docs.readthedocs.com/platform/stable/config-file/v2.html

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.14"

# Build documentation in the docs/source/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements-docs.txt
